export const environment = {
  production: false,
  PARAMETROS_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros/v1/',
  PROVEEDORES_SERVICE: '',
  CDPS_SERVICE: '',
  TIPO_COMPROMISO_ID: '111',
  TIPO_CONTRATO_ID: '112',
  PERFIL_CONTRATISTA_ID: '113',
  TIPOLOGIA_ESPECIFICA_ID: '114',
  MODALIDAD_SELECCION_ID: '115',
  REGIMEN_CONTRATACION_ID: '116',
  PROCEDIMIENTO_ID: '117',
  AMPARO_ID: '118',
  TIPO_CONTROL_ID: '119',
  CLASE_CONTRATISTA_ID: '120',
  VIGENCIA_ID: '121',
  TIPO_MONEDA: '122',
  TIPO_GASTO_ID: '123',
  ORIGEN_RECURSOS_ID: '124',
  ORIGEN_PRESUPUESTO_ID: '125',
  TEMA_GASTO_ID: '126',
  MEDIO_PAGO_ID: '127',
  TIPO_PERSONA_ID: '132',

  UNIDAD_EJECUCION_ID: '7',

  ORDEN_ID: '6534',
  CONTRATO_ID: '6535',
  CONVENIO_ID: '6536',

  CONTRATO_PSPAG_ID: '6546',

  PESO_COLOMBIANO_ID: '6634',
  
  AMPARO_CREC_ID: '6609',
  SUFICIENCIA_SMLV_ID: '6708',
  SUFICIENCIA_PORCENTAJE_ID: '6709',
};
